# -*- coding: utf-8 -*-
"""Build a ChatGPT Deep Research Clone with Streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JKAm6hu4BTekL5v0bZS33rmriY9VWIp2
"""

from openai import OpenAI
import os, json, itertools
from IPython.display import display, Markdown

from google.colab import userdata
openai_api_key = userdata.get('OpenAIChatGptFirstKey')

# Set up OpenAI API key in the os
os.environ['OPENAI_API_KEY'] = openai_api_key

# Connect to the OpenAI api
client = OpenAI()

# Define model inputs
MODEL = "gpt-4.1"
MODEL_MINI = "gpt-4.1-mini"
TOOLS = [{ "type": "web_search" }]

models = client.models.list()
for model in models.data:
    print(model.id)

# Developer message definition
developer_message = """
You are an expert Deep Researcher.
You provide complete and in depth research to the user.
"""

# Request the topic of research
topic = input("Please enter the research topic: ")
topic

"""### LLM asks questions"""

# Define here the prompt to clarify
prompt_to_clarify = f"""
Ask 5 numbered clarifying question to the user about the topic: {topic}.
The goal os the questions is to understand the intended purpose of the research.
Reply only with the questions
"""

# Get the OpenAI API to ask 5 clarifying questions
clarify = client.responses.create(
    model = MODEL_MINI,
    input = prompt_to_clarify,
    instructions = developer_message
)

clarify

# Get the questions
questions = clarify.output[0].content[0].text.split( "\n")
questions

# Ask each question to the user
answers = []
for question in questions:
  answer = input(question)
  answers.append(answer)

"""## Web Searches

### Goals and Queries


"""

# Write the prompt_goals prompt
prompt_goals = f"""
Using the user answers {answers} to  questions {questions}, write a goal sentence and 5 web search queries for the research about {topic}
Output: A json list of the goal and the 5 web search queries that will reach it.
Format: {{\"goal\": \"...\", \"queries\": [\"q1\", ....]}}
"""

# Use the responses API
goal_and_queries = client.responses.create(
    model = MODEL,
    input = prompt_goals,
    previous_response_id = clarify.id,
    instructions = developer_message
)

goal_and_queries

goal_and_queries.output[0].content[0].text

# Formatting and loading as JSON
plan = json.loads(goal_and_queries.output[0].content[0].text)

# Check the goal and the queries
print(plan["goal"])
print(plan["queries"])

# Store the goal and queries
goal = plan["goal"]
queries = plan["queries"]

"""### Web Search"""

# Print the first query
print(queries[0])

# Web search with the the responses endpoint
web_search = client.responses.create(
    model = MODEL,
    input = f"search: {queries[0]}",
    instructions = developer_message,
    tools = TOOLS
)

web_search

# Investigate the output
# Retrieve the id
web_search.output[1].id

web_search.output[1].content[0].text

# Build the function for the web searches
def run_search(q):
  web_search = client.responses.create(
    model = MODEL,
    input = f"search: {q}",
    instructions = developer_message,
    tools = TOOLS
  )
  return {"query": q,
          "resp_id": web_search.output[1].id,
          "research_output": web_search.output[1].content[0].text}

# Test the funtion
run_search(queries[0])

"""## Verifying if we have enough information to reach the goal"""

# Create a function that evaluates the outcome
def evaluate(collected):
  review = client.responses.create(
      model = MODEL,
      input = [
          {"role": "developer", "content": f"Research goal: {goal}"},
          {"role": "assistant", "content": json.dumps(collected)},
          {"role": "user", "content": "Does this information will fully satisfy the goal? Answer Yes or No only."}
      ],
      instructions = developer_message
  )
  return "yes" in review.output[0].content[0].text.lower()

# Verifying if we have enough info
collected = []
for _ in itertools.count():
  for q in queries:
    collected.append(run_search(q))
  if evaluate(collected):
    break

  # If no: perform 5 more questions
  more_searches = client.responses.create(
      model = MODEL,
      input = [
          {"role": "assistant", "content": f"Current data: {json.dumps(collected)}"},
          {"role": "user", "content": f"This has not met the goal: {goal}. Write 5 other web searchs to achieve the goal"}
      ],
      instructions = developer_message,
      previous_response_id = goal_and_queries.id
  )
  queries = json.loads(more_searches.output[0].content[0].text)

"""### Write the final report"""

# Use the responses endpoint to write the deep research report
report = client.responses.create(
    model = MODEL,
    input = [
        {"role": "developer", "content": (f"Write a complete and detailed report about research goal: {goal}"
                                        "Cite Sources inline using [n] and append a reference"
                                        "list mapping [n] to url")},
        {"role": "assistant", "content": json.dumps(collected)}],
    instructions = developer_message
)
print("\n=== FINAL REPORT ===")
display(Markdown(report.output[0].content[0].text))

!pip show openai

